FROM python:3.9-slim

WORKDIR /code

COPY ./ /code

RUN pip install --progress-bar off --no-cache-dir --upgrade -r /code/requirements.txt

EXPOSE 13457

HEALTHCHECK CMD curl --fail http://localhost:13457/_stcore/health

ENTRYPOINT ["streamlit", "run", "streamlit_main.py", "--server.port=13457", "--server.address=0.0.0.0"]